// SPDX-FileCopyrightText: © 2026 Privkey Inc.
// SPDX-License-Identifier: AGPL-3.0-or-later

#ifndef ERROR_CODES_H
#define ERROR_CODES_H

#include <stdint.h>

#define ERR_CAT_PROTOCOL 0x0100
#define ERR_CAT_FROST    0x0200
#define ERR_CAT_DKG      0x0300
#define ERR_CAT_STORAGE  0x0400
#define ERR_CAT_POLICY   0x0500
#define ERR_CAT_SESSION  0x0600
#define ERR_CAT_CRYPTO   0x0700
#define ERR_CAT_PIN      0x0800
#define ERR_CAT_SE       0x0900
#define ERR_CAT_PSBT     0x0A00
#define ERR_CAT_NOSTR    0x0B00

#define ERROR_CATEGORY(code) ((code) & 0xFF00)
#define ERROR_DETAIL(code)   ((code) & 0x00FF)

#define ERR_PROTOCOL_PARSE    (ERR_CAT_PROTOCOL | 0x01)
#define ERR_PROTOCOL_METHOD   (ERR_CAT_PROTOCOL | 0x02)
#define ERR_PROTOCOL_PARAMS   (ERR_CAT_PROTOCOL | 0x03)
#define ERR_PROTOCOL_INTERNAL (ERR_CAT_PROTOCOL | 0x04)

#define ERR_FROST_NO_SHARE        (ERR_CAT_FROST | 0x01)
#define ERR_FROST_INVALID_SESSION (ERR_CAT_FROST | 0x02)
#define ERR_FROST_NONCE_REUSE     (ERR_CAT_FROST | 0x03)
#define ERR_FROST_BAD_COMMITMENT  (ERR_CAT_FROST | 0x04)
#define ERR_FROST_AGGREGATION     (ERR_CAT_FROST | 0x05)
#define ERR_FROST_SIGN_FAILED     (ERR_CAT_FROST | 0x06)
#define ERR_FROST_THRESHOLD       (ERR_CAT_FROST | 0x07)
#define ERR_FROST_PARSE           (ERR_CAT_FROST | 0x08)
#define ERR_FROST_OVERFLOW        (ERR_CAT_FROST | 0x09)

#define ERR_DKG_INVALID_STATE   (ERR_CAT_DKG | 0x01)
#define ERR_DKG_DUPLICATE_SHARE (ERR_CAT_DKG | 0x02)
#define ERR_DKG_VERIFICATION    (ERR_CAT_DKG | 0x03)
#define ERR_DKG_TIMEOUT         (ERR_CAT_DKG | 0x04)
#define ERR_DKG_INVALID_PARAMS  (ERR_CAT_DKG | 0x05)

#define ERR_STORAGE_FULL          (ERR_CAT_STORAGE | 0x01)
#define ERR_STORAGE_NOT_FOUND     (ERR_CAT_STORAGE | 0x02)
#define ERR_STORAGE_CORRUPT       (ERR_CAT_STORAGE | 0x03)
#define ERR_STORAGE_DECRYPT       (ERR_CAT_STORAGE | 0x04)
#define ERR_STORAGE_NOT_INIT      (ERR_CAT_STORAGE | 0x05)
#define ERR_STORAGE_CRYPTO        (ERR_CAT_STORAGE | 0x06)
#define ERR_STORAGE_INVALID       (ERR_CAT_STORAGE | 0x07)
#define ERR_STORAGE_IO            (ERR_CAT_STORAGE | 0x08)
#define ERR_STORAGE_INVALID_DATA  (ERR_CAT_STORAGE | 0x09)
#define ERR_STORAGE_INVALID_GROUP (ERR_CAT_STORAGE | 0x0A)
#define ERR_STORAGE_MIGRATION     (ERR_CAT_STORAGE | 0x0B)
#define ERR_STORAGE_ENCRYPT       (ERR_CAT_STORAGE | 0x0C)

#define ERR_POLICY_DENIED       (ERR_CAT_POLICY | 0x01)
#define ERR_POLICY_INVALID_SIG  (ERR_CAT_POLICY | 0x02)
#define ERR_POLICY_EXPIRED      (ERR_CAT_POLICY | 0x03)
#define ERR_POLICY_FEE_EXCEEDED (ERR_CAT_POLICY | 0x04)
#define ERR_POLICY_NOT_FOUND    (ERR_CAT_POLICY | 0x05)
#define ERR_POLICY_STORAGE      (ERR_CAT_POLICY | 0x06)
#define ERR_POLICY_VERSION      (ERR_CAT_POLICY | 0x07)
#define ERR_POLICY_NO_BUNDLE    (ERR_CAT_POLICY | 0x08)
#define ERR_POLICY_HASH         (ERR_CAT_POLICY | 0x09)
#define ERR_POLICY_MALFORMED    (ERR_CAT_POLICY | 0x0A)

#define ERR_SESSION_INVALID_STATE   (ERR_CAT_SESSION | 0x01)
#define ERR_SESSION_NOT_FOUND       (ERR_CAT_SESSION | 0x02)
#define ERR_SESSION_EXPIRED         (ERR_CAT_SESSION | 0x03)
#define ERR_SESSION_DUPLICATE       (ERR_CAT_SESSION | 0x04)
#define ERR_SESSION_INVALID_LEN     (ERR_CAT_SESSION | 0x05)
#define ERR_SESSION_REPLAY          (ERR_CAT_SESSION | 0x06)
#define ERR_SESSION_NOT_PARTICIPANT (ERR_CAT_SESSION | 0x07)

#define ERR_CRYPTO_RNG_FAIL    (ERR_CAT_CRYPTO | 0x01)
#define ERR_CRYPTO_VERIFY_FAIL (ERR_CAT_CRYPTO | 0x02)
#define ERR_CRYPTO_SIGN_FAIL   (ERR_CAT_CRYPTO | 0x03)
#define ERR_CRYPTO_HASH_FAIL   (ERR_CAT_CRYPTO | 0x04)

#define ERR_PIN_REQUIRED  (ERR_CAT_PIN | 0x01)
#define ERR_PIN_INVALID   (ERR_CAT_PIN | 0x02)
#define ERR_PIN_LOCKED    (ERR_CAT_PIN | 0x03)
#define ERR_PIN_MUST_WAIT (ERR_CAT_PIN | 0x04)
#define ERR_PIN_BRICKED   (ERR_CAT_PIN | 0x05)

#define ERR_SE_INVALID_PARAM   (ERR_CAT_SE | 0x01)
#define ERR_SE_NOT_PROVISIONED (ERR_CAT_SE | 0x02)
#define ERR_SE_COMM_FAIL       (ERR_CAT_SE | 0x03)
#define ERR_SE_LOCKED          (ERR_CAT_SE | 0x04)
#define ERR_SE_NOT_INIT        (ERR_CAT_SE | 0x05)

#define ERR_PSBT_PARSE   (ERR_CAT_PSBT | 0x01)
#define ERR_PSBT_INVALID (ERR_CAT_PSBT | 0x02)
#define ERR_PSBT_SIGN    (ERR_CAT_PSBT | 0x03)

#define ERR_NOSTR_PARSE   (ERR_CAT_NOSTR | 0x01)
#define ERR_NOSTR_DECRYPT (ERR_CAT_NOSTR | 0x02)
#define ERR_NOSTR_SIGN    (ERR_CAT_NOSTR | 0x03)
#define ERR_NOSTR_RELAY   (ERR_CAT_NOSTR | 0x04)

const char *error_to_string(int code);
const char *error_name(int code);
const char *error_category_name(int code);
int error_to_jsonrpc_code(int code);

#define PROTOCOL_ERR_PARSE    ERR_PROTOCOL_PARSE
#define PROTOCOL_ERR_METHOD   ERR_PROTOCOL_METHOD
#define PROTOCOL_ERR_PARAMS   ERR_PROTOCOL_PARAMS
#define PROTOCOL_ERR_INTERNAL ERR_PROTOCOL_INTERNAL
#define PROTOCOL_ERR_SHARE    ERR_FROST_NO_SHARE
#define PROTOCOL_ERR_SIGN     ERR_FROST_SIGN_FAILED
#define PROTOCOL_ERR_STORAGE  ERR_STORAGE_IO

#define STORAGE_OK                  0
#define STORAGE_ERR_NOT_INIT        ERR_STORAGE_NOT_INIT
#define STORAGE_ERR_CRYPTO_NOT_INIT ERR_STORAGE_CRYPTO
#define STORAGE_ERR_INVALID_GROUP   ERR_STORAGE_INVALID_GROUP
#define STORAGE_ERR_INVALID_DATA    ERR_STORAGE_INVALID_DATA
#define STORAGE_ERR_NO_SLOT         ERR_STORAGE_FULL
#define STORAGE_ERR_IO              ERR_STORAGE_IO
#define STORAGE_ERR_NOT_FOUND       ERR_STORAGE_NOT_FOUND
#define STORAGE_ERR_DECRYPT         ERR_STORAGE_DECRYPT
#define STORAGE_ERR_MIGRATION       ERR_STORAGE_MIGRATION
#define STORAGE_ERR_ENCRYPT         ERR_STORAGE_ENCRYPT

#define SESSION_ERR_INVALID_STATE   ERR_SESSION_INVALID_STATE
#define SESSION_ERR_NOT_PARTICIPANT ERR_SESSION_NOT_PARTICIPANT
#define SESSION_ERR_INVALID_LEN     ERR_SESSION_INVALID_LEN
#define SESSION_ERR_DUPLICATE       ERR_SESSION_DUPLICATE

#define POLICY_ERR_NOT_FOUND     ERR_POLICY_NOT_FOUND
#define POLICY_ERR_INVALID_SIG   ERR_POLICY_INVALID_SIG
#define POLICY_ERR_STORAGE       ERR_POLICY_STORAGE
#define POLICY_ERR_VERSION       ERR_POLICY_VERSION
#define POLICY_ERR_NO_BUNDLE     ERR_POLICY_NO_BUNDLE
#define POLICY_ERR_HASH_MISMATCH ERR_POLICY_HASH
#define POLICY_ERR_DENIED        ERR_POLICY_DENIED
#define POLICY_ERR_MALFORMED     ERR_POLICY_MALFORMED

#endif
