#!/usr/bin/env python3
# SPDX-FileCopyrightText: © 2026 PrivKey LLC
# SPDX-License-Identifier: MIT
"""Generate components/frost_tr/rust/src/vectors.rs from the ZF test vectors.

vectors.json is a byte-for-byte copy of tests/helpers/vectors.json from the
frost-secp256k1-tr 3.0.0 crate; its SHA-256 is checked here and in the crate's
tests. Run with --check in CI to fail when the generated file is stale.
"""
import hashlib
import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
JSON = ROOT / "components/frost_tr/rust/vectors/vectors.json"
OUT = ROOT / "components/frost_tr/rust/src/vectors.rs"
SHA256 = "0ac120db0ae51143b04e74edfc90cf62e29e58f5980308e5efb0da039bfdc3ff"


def arr(hexstr):
    return "[" + ", ".join(f"0x{b:02x}" for b in bytes.fromhex(hexstr)) + "]"


def render():
    raw = JSON.read_bytes()
    digest = hashlib.sha256(raw).hexdigest()
    if digest != SHA256:
        sys.exit(f"{JSON} sha256 {digest} != {SHA256}")
    d = json.loads(raw)
    inputs = d["inputs"]
    shares = {s["identifier"]: s["participant_share"] for s in inputs["participant_shares"]}
    r1 = {o["identifier"]: o for o in d["round_one_outputs"]["outputs"]}
    r2 = {o["identifier"]: o for o in d["round_two_outputs"]["outputs"]}
    lines = [
        "// @generated by scripts/gen-frost-tr-vectors.py from vectors/vectors.json",
        f"// (frost-secp256k1-tr 3.0.0 tests/helpers/vectors.json, sha256 {SHA256}).",
        "// Do not edit by hand.",
        "",
        f"pub const MIN_SIGNERS: u16 = {int(d['config']['MIN_PARTICIPANTS'])};",
        f"pub const VERIFYING_KEY: [u8; 33] = {arr(inputs['verifying_key_key'])};",
        f"pub const MESSAGE: &[u8] = &{arr(inputs['message'])};",
        f"pub const SIGNATURE: [u8; 64] = {arr(d['final_output']['sig'])};",
        "",
        "pub struct Participant {",
        "    pub identifier: u16,",
        "    pub signing_share: [u8; 32],",
        "    pub hiding_nonce: [u8; 32],",
        "    pub binding_nonce: [u8; 32],",
        "    pub hiding_commitment: [u8; 33],",
        "    pub binding_commitment: [u8; 33],",
        "    pub signature_share: [u8; 32],",
        "}",
        "",
        "pub const PARTICIPANTS: &[Participant] = &[",
    ]
    for ident in inputs["participant_list"]:
        o = r1[ident]
        lines += [
            "    Participant {",
            f"        identifier: {ident},",
            f"        signing_share: {arr(shares[ident])},",
            f"        hiding_nonce: {arr(o['hiding_nonce'])},",
            f"        binding_nonce: {arr(o['binding_nonce'])},",
            f"        hiding_commitment: {arr(o['hiding_nonce_commitment'])},",
            f"        binding_commitment: {arr(o['binding_nonce_commitment'])},",
            f"        signature_share: {arr(r2[ident]['sig_share'])},",
            "    },",
        ]
    lines += ["];", ""]
    return "\n".join(lines)


def main():
    text = render()
    if "--check" in sys.argv:
        if not OUT.exists() or OUT.read_text() != text:
            sys.exit(f"{OUT} is stale; run scripts/gen-frost-tr-vectors.py")
        return
    OUT.write_text(text)


if __name__ == "__main__":
    main()
